### ISSUE TITLE
Multitap support

### ISSUE THREAD

**Issue by chmcarro** [redacted173/sd2snes#29] opened 2021-11-13 05:51 UTC
In Wario Blast -after selecting battle mode, input for players 3 and 4 is not received when using a multitap adapter.

**Comment by redacted173** [comment] 2021-11-14 02:27
I don't have a multitap to test, unfortunately.  When you get to the following menu and hit A on controller 3/4 it does not set these as "ON".  Correct?

Or can you set the them to ON but once you get into the game the controllers don't control the characters?

Do you have the original SGB to test the multitap with?

Does the multitap work with SNES games?

Do controllers 3/4 work in Bomberman GB on SD2SNES SGB?

A lot of the code to get controller data runs on the SNES and then it sets up the SGB.  The emulators running SGB seem to expect the multitap to be plugged into port 2 and player 1 controller to be plugged into port 1 on the SNES.  Then multitap port 1,2,3 are player 2,3,4, respectively.  Not sure if this is the expected behavior, though.  Is this how you have your multitap setup?

Are you running an unmodified sgb_snes.bin (either SGB1 or SGB2) ROM image?

![wario_blast_player_enable_circled](https://user-images.githubusercontent.com/67377137/141664804-90b48413-efd0-41f6-ab8b-7f5b375e6f33.png)

**Comment by chmcarro** [comment] 2021-11-14 02:52
Thank you very much for the help! I have both an SD2SNES and SGB2. The multitap works on the SD2SNES for SNES games, but not the SGB core. 

ON SGB v7 on released SD2SNES firmware or on the SD2SNES beta firmware, the same behavior is seen:

The"A" button press does not switch the value from "off" to "on". I also tested with Bomerman GB2. Selecting up or down for controllers 3 and 4 do not work to activate player 3 and 4.

Players 3 and 4 are with the multitap on SNES port 2, with multitap positions 2 and 3.
Players 3 and 4 work on my actual SGB2 with Everdrive GB for Wario Blast and Bomberman GB2.

**Comment by chmcarro** [comment] 2021-11-14 02:58
I believe my sgb2_snes,bin is unmodfied - CRC32 CB176E45

**Comment by redacted173** [comment] 2021-11-15 22:45
Try it with the attached fpga_sgb.bit (SD2SNES classic only) file in your sd2snes/ folder on the SD card.  I didn't see a problem with the SD2SNES/FXPAK pro, but on the classic it looks like the verilog compiler doesn't treat an implicit default in case statements as I would expect.  This causes the button state for controllers 2 and 3 to always reset even when the game supports 3+.  Not sure whether this is a feature or bug in the 10+ year old Xilinx compiler, but it's easy to work around.

The bug was triggered and later tested by hacking sgb_snes.bin to use controller 0's state for all controllers since I don't own a multitap.

Thanks for the bug report.

[multitap_xilinx_compiler_issue_fix.zip](https://github.com/redacted173/sd2snes/files/7542033/multitap_xilinx_compiler_issue_fix.zip)

**Comment by chmcarro** [comment] 2021-11-15 23:04
Thank you! 

Firmware v1.11.0 beta - Gameboy games do not boot with the provided fpga_sgb.bit
Firmware v1.10.3_sgb07 - All 4 controller inputs working as expected for Wario Blast and Bomberman GB.

**Comment by redacted173** [comment] 2021-11-16 00:21
I forgot to mention the fix is based on sgb07.  I haven't kept up with all the changes in ikari's repo so it's not too surprising it doesn't work with a different release.  I checked in the fix and made a pull request here: https://github.com/mrehkopf/sd2snes/pull/168.  Hopefully ikari can merge it into a future release when he has time.

https://github.com/mrehkopf/sd2snes/pull/168

**Closed as completed by redacted173** 2021-11-16 00:21 UTC
