### ISSUE TITLE
Mortal Kombat: Freeze in Midway Presents Logo

### ISSUE THREAD

**Issue by ErivandoBR** [redacted173/sd2snes#6] opened 2020-06-29 14:10 UTC
Mortal Kombat: Freeze in Midway Presents Logo
Music and IGH continues working.

Firmware 1.10.3_sgb00 and 1.10.3_sgb01
Classic SD2SNES Rev F

**Comment by Goldanas** [comment] 2020-07-01 02:32
Happens on SD2SNES Pro as well. (Running on a SNES; can't speak to a Super NT)

**Comment by redacted173** [comment] 2020-07-01 15:10
Can't reproduce on MK1 (256KB CRC-32 90EB0929).

**Comment by Goldanas** [comment] 2020-07-01 15:29
That's the CRC-32 of what I'm using. It's possible it's fixed on your internal builds with that transfer link interrupt addition (or some other interrupt cleanups), and just not working on the sgb01 release. The failure behavior is very similar to what happens in Bomberman Quest when selecting Battle in that same release.

**Comment by Goldanas** [comment] 2020-07-04 02:10
I can confirm that the game loads and runs as expected in the SGB02 release.

**Comment by ErivandoBR** [comment] 2020-07-04 02:52
Fixed in SGB02. Thanks!

**Closed as completed** 2020-07-04 02:53 UTC
